### ISSUE TITLE
Can't import the named export 'AlwaysDepth' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by abdulrehman1937** [vanruesc/postprocessing#312] opened 2021-08-30 20:11 UTC
### Description of the bug

Started getting this error after postprocessing v6.22.4 was released.

### To Reproduce

I am using depth of field effect. I can not run my app. It does not compile.

### Expected behaviour

App should compile and run smoothly like before.

### Screenshots

Added

### Library versions used

 - "@react-three/postprocessing": "^2.0.5",
<img width="906" alt="Screenshot 2021-08-31 at 1 09 55 AM" src="https://user-images.githubusercontent.com/44475042/131398957-bad6d718-257e-4506-87c1-45af077c5767.png">

### Desktop

 - MacOs BigSur 11.5.2
 -Chrome 92.0.4515.159

**Comment by Craaftx** [comment] 2021-08-30 20:48
Same issue with
`@react-three/postprocessing": "^2.0.5`
`postprocessing": "6.22.4`

Desktop :
Windows 11 21H2
Firefox 91.0.2 (64 bits)

**Comment by vanruesc** [comment] 2021-08-30 21:05
Hi, thanks for the report!

What's your node.js version and which bundler are you using? I'd like to reproduce this issue locally.

It looks like `postprocessing` is being imported as a native ES6 module and transitive imports from `three` are treated the same way although `three` is not of type module.

**Comment by abdulrehman1937** [comment] 2021-08-30 21:32
Node v v16.5.0
Bundler webpack (using creat-react-app)

**Comment by vanruesc** [comment] 2021-08-30 21:42
Mh, I just found this: https://github.com/formatjs/formatjs/issues/1395

Looks like CRA simply doesn't support `.mjs` imports which is a bummer. I changed the extension because it enables blazing fast Ava.js testing without esm.js when importing stuff from `postprocessing` like `Pass` in other projects.

I guess I'll change it back to `.esm.js` for now. I wonder how CRA would _react_ to `type: module` in `package.json`.

**Comment by vanruesc** [comment] 2021-08-30 22:07
Fixed in `postprocessing@6.22.5`.

**Closed by vanruesc** 2021-08-30 22:07 UTC
Labels: regression, react

**Comment by vanruesc** [comment] 2022-02-07 02:02
@abdulrehman1937 I've changed the bundle name to `postprocessing.mjs` in `postprocessing@6.24.0`. [This comment](https://github.com/facebook/create-react-app/issues/10356#issuecomment-1000016251) suggests that CRA 5.0.0 can now handle `.mjs` bundles. Let me know if there are any issues!
