### ISSUE TITLE
LUTEffect produces incorrect results

### ISSUE THREAD

**Issue by vanruesc** [vanruesc/postprocessing#250] opened 2021-01-05 22:56 UTC
### Description of the bug

The newly added `LUTEffect` currently produces inaccurate results. With a neutral LUT, the image becomes darker even when using `HalfFloatType` buffers and a `highp` LUT sampler with `FloatType` data. Upscaling with the `TetrahedralUpscaler` via `LookupTexture3D.scaleUp()` produces banding artifacts.

### To Reproduce

The following example uses a neutral LUT which incorrectly darkens the image: https://codesandbox.io/s/fervent-kapitsa-3jikk

When using a 2x2x2 LUT, the image quality is greatly reduced which does not happen here: https://threejsfundamentals.org/threejs/lessons/threejs-post-processing-3dlut.html

### Expected behavior

An identity LUT should not change the image. Color space should also not matter if a neutral LUT is used, but linear input colors currently produce even worse results.

### Screenshots

Images taken from https://github.com/vanruesc/postprocessing/issues/231#issuecomment-753638346:

| Neutral LUT 32 | Neutral LUT scaled up to 128 |
|-|-|
| ![image](https://user-images.githubusercontent.com/5507503/103483077-70ccf400-4ded-11eb-8d4a-5f4942e63ae4.png) | ![image](https://user-images.githubusercontent.com/5507503/103483061-572bac80-4ded-11eb-960f-30537328780d.png) |

### Library versions used

 - Three: 0.124.0
 - Post Processing: 6.19.0

### Desktop

 - Windows 10
 - Firefox 84.0.1
 - NVIDIA GTX 1060

**Comment by gkjohnson** [comment] 2021-01-06 04:43
I took a little time to look into some of the differences and pulling the samples by half a pixel so sampling begins at the edge pixel center as I suggested in https://github.com/vanruesc/postprocessing/issues/231#issuecomment-754894171 reduces the amount of color differences with the neutral LUT.

I also found that the sampling of 2d texture sampling was not exactly matching the 3d texture sampling especially in the 2³ sized LUT case so I've updated that shader function, as well. The sampling in 2D vs 3D texture mode matches very well at 32³ LUTs and higher but there are some noticeable differences with lower sizes. A second set of eyes on that would be very helpful. I'll try the version you referenced at three.js fundamentals and see if that implementation looks more right.

I haven't updated the TetrahedralUpscaler yet but that should probably account for the half pixel inset, as well, because you can see there is a darkening when upscaling.

Here's the commit with the changes:

https://github.com/gkjohnson/threejs-sandbox/commit/ff17335a976f0938d722c9673e7175caa622c610

And here's the new demo:

https://gkjohnson.github.io/threejs-sandbox/3d-lut/

It includes more neutral LUTs of various sizes and a new "sponza" image for testing -- select neutral LUTs and toggle the effect to see the differences. 32³ and higher sizes don't have noticeable differences to me unless I zoom in in an image editing app. @AlexDaniel take a look and let me know if this is more what you expect.

@vanruesc 
> When using a 2x2x2 LUT, the image quality is greatly reduced which does not happen here: https://threejsfundamentals.org/threejs/lessons/threejs-post-processing-3dlut.html

Can you elaborate on this?

**Comment by AlexDaniel** [comment] 2021-01-06 06:50
@gkjohnson Taking a quick look, I can't see any differences in colors at all.

Except for this bug:

![image](https://user-images.githubusercontent.com/5507503/103737746-7ac44200-4ffb-11eb-9ef4-52ba35ad6beb.png)

![image](https://user-images.githubusercontent.com/5507503/103737776-8d3e7b80-4ffb-11eb-8d79-9bc22d488905.png)

Note that these differences are very sharp and completely off. Definitely a bug somewhere. These appear only with 4³ luts. Bigger and smaller luts are fine, and the issue disappears when using tetrahedralResize.

That said, the result is fantastic. Yes, this is what I expected. Amazing work!

**Comment by AlexDaniel** [comment] 2021-01-06 07:00
OK, maybe I spoke too soon because tetrahedralResize definitely affects overall image brightness (it becomes darker). The effect is really small though.

As for reproducing the bug above, here are the settings:
![image](https://user-images.githubusercontent.com/5507503/103738980-916b9880-4ffd-11eb-8a2f-e7c27973a6c5.png)

**Comment by vanruesc** [comment] 2021-01-06 14:20
@gkjohnson thanks for taking the time to look into this. The  latests changes greatly improve results, but I still noticed slight darkening and imperfections with the neutral LUTs.

I found [this article](https://developer.nvidia.com/gpugems/gpugems2/part-iii-high-quality-rendering/chapter-24-using-lookup-tables-accelerate-color) which says that the sampling coordinates for LUTs should be adjusted like so:
```glsl
(lutSize - 1.0) / lutSize * oldCoord + 1.0 / (2.0 * lutSize)
```
Which boils down to a constant scale and offset:
```glsl
const float scale = (lutSize - 1.0) / lutSize;
const float offset = 1.0 / (2.0 * lutSize);
vec3 uvw = scale * rgb + offset;
```
[This is similar to what you're already doing](https://github.com/gkjohnson/threejs-sandbox/blob/6af64c6eb1de375063ab784b907a060708680301/3d-lut/src/shaders/LUTShader.js#L57-L59), but not quite the same formular.

After adopting this scale/offset calculation, I no longer see any darkening or banding. This also fixes linear input colors. However, with linear input, 2³ and 4³ LUTs produce artifacts which might just be due to insufficient precision in the darker spectrum.

I don't know how the scale/offset change translates to the tetrahedral upscaling algorithm. I've applied your latest changes and the upscaler seems to work correctly; scaling a 2³ LUT up to 32³ works as intended. I think we should add a unit test to check if the result matches a 32³ neutral LUT, just in case.

**Comment by vanruesc** [comment] 2021-01-06 14:46
> This is similar to what you're already doing, but not quite the same formular.

Sorry got confused by the math there. The result should be the same.

I wonder why I don't see any darkening in my local setup. Maybe it's because I'm using half float frame buffers 🤔

**Comment by gkjohnson** [comment] 2021-01-06 16:45
@AlexDaniel 

> Except for this bug:

Ugh -- that 2D LUT sampling function is so difficult. It seems the referenced implementation isn't perfect, either, unless I've ported it incorrectly. I'll have to fiddle with it more when I have more time.

@vanruesc 

> I still noticed slight darkening and imperfections with the neutral LUTs.

Looking at it with fresh eyes I do see a _very_ small change but just in the background color when toggling the effect with the 2³ LUT but it's only off by 1 bit: the background should be `0x151515` but it's converted to `0x151615`. I'm using HalfFloatType buffers, now too and if I change the background to a different color it no longer changes. Is that what you're referring to? Perhaps you can try the same value to see if it happens in your implementation. I'm wondering if this is _actually_ a result of using linear interpolation.

> However, with linear input, 2³ and 4³ LUTs produce artifacts which might just be due to insufficient precision in the darker spectrum.

Can you elaborate on this? Are you still seeing issues after you second post? Is the issue I mentioned above the only change you're seeing (aside from the 2d lut sampling case)?

> I don't know how the scale/offset change translates to the tetrahedral upscaling algorithm. 

It's possible this is already correct and the issues I was seeing previously after upscaling were due to the sampling bug I fixed in my edit. I'll have to take another look to verify.

**Comment by AlexDaniel** [comment] 2021-01-06 19:13
I don't know if this is of any use, but another open-source project with lut filter implementation is obs studio:
* shader here: https://github.com/obsproject/obs-studio/blob/master/plugins/obs-filters/data/color_grade_filter.effect
* other processing here: https://github.com/obsproject/obs-studio/blob/master/plugins/obs-filters/color-grade-filter.c
* Tetrahedral interpolation seems to be supported as well: https://github.com/obsproject/obs-studio/commit/34d70c6832348ef37a70b25d2c2a9a757a00833e

**Comment by vanruesc** [comment] 2021-01-06 23:38
@gkjohnson I should've mentioned that I was using a 3D sampler during my tests earlier. With the new scale/offset adjustment, the hardware interpolation produces great results even with a 2³ LUT. The artifacts I was talking about appear when I move the gamma correction after the LUT effect. The artifacts disappear when a 8³ LUT or larger is used. It's worth noting that the linear colors of the Sponza scene are very dark which is a bit of a challenge for a LUT.

For the following comparisons I have used `FloatType` LUTs and [the new sampling algorithm](https://github.com/gkjohnson/threejs-sandbox/blob/master/3d-lut/src/shaders/LUTShaderFunctions.js) for 2D samplers.

| Ground truth | Linear version |
|-|-|
| <img src="https://user-images.githubusercontent.com/9214917/103831244-f8c82d80-507b-11eb-9a6e-26ac7e64b078.jpg"> | <img src="https://user-images.githubusercontent.com/9214917/103831595-af2c1280-507c-11eb-8c88-14134c23a7c9.jpg"> |

#### sRGB Input

Colors are converted to sRGB prior to being used as coordinates to sample the neutral LUT.

| Size | 3D sampler | 2D sampler |
|-|-|-|
| __2³__ | ![srgb-02-2x2x2-3d](https://user-images.githubusercontent.com/9214917/103831277-0a113a00-507c-11eb-8a0b-4d9196990431.jpg) | ![srgb-04-2x2x2-2d](https://user-images.githubusercontent.com/9214917/103831340-26ad7200-507c-11eb-8169-37f64a18cf26.jpg) |
| __32³__ | ![srgb-03-32x32x32-3d](https://user-images.githubusercontent.com/9214917/103831315-1a291980-507c-11eb-87e4-9521fcb384e9.jpg) | ![srgb-05-32x32x32-2d](https://user-images.githubusercontent.com/9214917/103831429-59576a80-507c-11eb-872d-6945fb5d68de.jpg) |

3D: No issues.
2D: Artifacts in the golden embroidery on the red curtain.

<img width="350" src="https://user-images.githubusercontent.com/9214917/103832048-b69feb80-507d-11eb-9c1a-87bb0ae12cda.jpg">

#### Linear Input

Colors are not converted and are used as-is (linear) to sample the neutral LUT.

| Size | 3D sampler | 2D sampler |
|-|-|-|
| __2³__ | ![linear-03-2x2x2-3d](https://user-images.githubusercontent.com/9214917/103831940-7d677b80-507d-11eb-985d-59418958d626.jpg) | ![linear-04-32x32x32-3d](https://user-images.githubusercontent.com/9214917/103831969-8e17f180-507d-11eb-8b3c-5b0c49b16692.jpg) |
| __32³__ | ![linear-05-2x2x2-2d](https://user-images.githubusercontent.com/9214917/103832002-9a9c4a00-507d-11eb-83d1-c6ae996c4d01.jpg) | ![linear-06-32x32x32-2d](https://user-images.githubusercontent.com/9214917/103832024-a5ef7580-507d-11eb-8db9-e7198dd7ddb6.jpg) |

3D: Inaccurate colors when using a LUT smaller than 8³.
2D: Similar results as 3D LUT when using 2³, but lots of artifacts on curtains when using larger LUTs.

@AlexDaniel Thanks for those references. That shader does indeed use tetrahedral interpolation with 3D samplers which might come in handy if we add that feature in the future. Unfortunately, this implementation can probably not be used to fix our LUT 2D sampling/interpolation problem.

I'm currently very tempted to drop support for 2D LUTs / WebGL 1 😄

**Comment by vanruesc** [comment] 2021-01-07 12:34
Sorry I had a mix-up in the Linear Input comparison table: 3D 32³ and 2D 2³ were swapped. Fixed now.

**Comment by vanruesc** [comment] 2021-01-07 12:54
> I'm using HalfFloatType buffers, now too and if I change the background to a different color it no longer changes. Is that what you're referring to? Perhaps you can try the same value to see if it happens in your implementation.

Yes, that is what I meant by slight darkening and imperfections. I tried out `0x151515` with half float buffers and observed the following:

| Size | 3D sampler | 2D sampler |
|-|-|-|
| __2³__ | 0x151615 | 0x151515 |
| __32³__ | 0x151515 | 0x151515 |

I think that the 3D sampler case is actually the correct behaviour even though it's off by one bit at 2³.

**Comment by gkjohnson** [comment] 2021-01-08 05:48
> I'm currently very tempted to drop support for 2D LUTs / WebGL 1 😄

Heh, I wouldn't blame you. But it was driving me nuts because it should definitely be solvable so I think I got to the bottom of the 2d sampling artifacts. I rewrote the sampling function from scratch (https://github.com/gkjohnson/threejs-sandbox/commit/c426602df8668884601dc23144eb98564e5998d4) and in doing sound found a graphics API (or NVidia driver?) quirk that caused sampling the LUT to produce unexpected results. Specifically the important change is that the LUTs `minFilter` field must be set to `LinearFilter` otherwise samples seem to have artifacts. I set it on the 3d texture, as well. There are a couple fixes I made in the sample function compared to my previous version, too.

If you're interested in seeing the raw artifacts here's a JSFiddle with a minimum repro case using the car image. The comments above the data texture initialization and in the shader should explain the important bits: https://jsfiddle.net/mbqyazsj/1/.

I'm no longer seeing the artifacts in the blue curtain with a 4³ 2D LUT and I'll say I'm more confident in the 2d lut sampling strategy now until you guys inevitably find something else that's wrong 😄

> I think that the 3D sampler case is actually the correct behaviour even though it's off by one bit at 2³.

Yeah I'm not exactly sure what could be causing that otherwise. It's correct in the R and B dimensions 🤔 

Regarding gamma correction I'm seeing some color precision loss when moving the gamma correction step after the LUT sampling (I'm using three.js' postprocessing as a foundation) but I'm gonna chalk that up to something else related to that stack. Do you mind trying the new sample function and texture settings (hopefully for a last time) to see if you still see issues?

**Comment by AlexDaniel** [comment] 2021-01-08 05:53
> in doing sound found a graphics API (or NVidia driver?)

I see this with amdgpu on linux:
![image](https://user-images.githubusercontent.com/5507503/103979459-83954f00-5186-11eb-9198-276e12a0cfed.png)

**Comment by gkjohnson** [comment] 2021-01-08 07:41
That's what I see, too.

Thinking about it more it's probably intended behavior. With a high gradient for the sampled pixels around edges of the car it probably switches to minification filtering which defaults to `NEAREST_FILTER` whereas the rest of the pixels are using magnified filtering with `LINEAR_FILTER` giving the above image. I guess it hadn't occurred to me that you could get different sampling behavior based on the samples of another image like this but I suppose it makes sense!

**Comment by AlexDaniel** [comment] 2021-01-08 07:44
@gkjohnson can you elaborate? Is it because the image is scaled? So it's not a concern for the purposes of postprocessing library?

**Comment by gkjohnson** [comment] 2021-01-08 16:39
It does effect the library -- the `minFilter` and `magFilter` of the 2D and 3D LUT textures must be set to `LINEAR_FILTER`.

In order for the GPU to determine whether to use minification filtering or which mipmap to use when sampling a texture the derivative of the value passed into the uv argument of the `texture( sampler, uv )` function is taken. See [here](https://community.khronos.org/t/mipmap-level-calculation-using-dfdx-dfdy/67480) for more on how mip map levels are calculated. A higher gradient means the value is changing faster and should use a smaller mip map. Typically a UV coordinate that's been interpolated over a triangle is passed in which means the value gets larger as the triangle gets smaller or tilts relative to the camera.

In this case, though, we're passing the sampled color from an image into the `texture()` function meaning the gradient is how much the color of a pixel is changing which is highest at high contrast parts of the image such as at the edges of the car.

**Comment by vanruesc** [comment] 2021-01-08 17:42
@gkjohnson Thanks for the super fast fix and great explanation!

I've tested the new shader with a neutral LUT applied to linear input colors and found no issues.

| Size | 3D sampler | 2D sampler |
|-|-|-|
| __2³__ | ![linear-03-2x2x2-3d](https://user-images.githubusercontent.com/9214917/103831940-7d677b80-507d-11eb-985d-59418958d626.jpg) | ![linear-2x2x2-2d](https://user-images.githubusercontent.com/9214917/104023274-b6106d80-51c1-11eb-8bf7-313bf6c3c10e.jpg) |
| __32³__ | ![linear-04-32x32x32-3d](https://user-images.githubusercontent.com/9214917/103831969-8e17f180-507d-11eb-8b3c-5b0c49b16692.jpg) | ![linear-32x32x32-2d](https://user-images.githubusercontent.com/9214917/104023350-d4766900-51c1-11eb-8d67-130243103815.jpg) |

The artifacts are gone and the results match perfectly at both sizes. I've also tested with sRGB input and saw the same results.

When the neutral 2D/3D LUTs are applied to `0x151515`, we get these results:

| Size | 3D sampler | 2D sampler |
|-|-|-|
| __2³__ | 0x151615 | 0x161615 |
| __32³__ | 0x151515 | 0x151515 |

The small difference at 2³ is interesting but shouldn't be a problem.

One thing I had to change in the shader was [this modf](https://github.com/gkjohnson/threejs-sandbox/blob/704384775c5774c1749200ca7bb31f100366caab/3d-lut/src/shaders/LUTShaderFunctions.js#L10-L11) which is [not supported](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/modf.xhtml) in WebGL 1. I replaced it with this:
```glsl
float interp = fract(slice);
float slice0 = slice - interp;
```

**Comment by vanruesc** [comment] 2021-01-08 17:48
> The artifacts are gone and the results match perfectly at both sizes.

I spoke too soon this time. There is a small difference at 2³. I was wondering whether the [uvw calculation](https://github.com/gkjohnson/threejs-sandbox/blob/704384775c5774c1749200ca7bb31f100366caab/3d-lut/src/shaders/LUTShader.js#L55-L57) is correct for the 2D case.

**Comment by vanruesc** [comment] 2021-01-08 17:57
I've tested again with sRGB input and found that both 2D and 3D samplers produce the same results in this case.

**Comment by gkjohnson** [comment] 2021-01-08 19:09
🎉 

> One thing I had to change in the shader was this modf which is not supported in WebGL 1. I replaced it with this:

Good catch! Didn't realize it wasn't supported. Your fix looks good.

> I was wondering whether the uvw calculation is correct for the 2D case.

> I've tested again with sRGB input and found that both 2D and 3D samplers produce the same results in this case.

Can you clarify if you are seeing issues? Between these two comments it's not clear to me if there is still a problem and in what cases.

Regarding the UVW calculation the 2D LUT sampling function is intended to sample colors in the same way as the texture 3d sampling function so the input for both functions should be the same.

**Comment by vanruesc** [comment] 2021-01-08 20:09
The new interpolation algorithm matches the 3D interpolation very closely, but when the input colors are darker, as is the case with linear input colors, then there are small differences in results, even with LUTs of size 32³. Here's a diff of the 3D/2D results with dark linear input colors:

| | 2³ | 32³ |
|-|-|-|
| Diff | ![2x2x2-diff](https://user-images.githubusercontent.com/9214917/104055860-c3dce780-51ef-11eb-985e-ff555783fae9.png) | ![32x32x32-diff](https://user-images.githubusercontent.com/9214917/104055890-d1926d00-51ef-11eb-90b0-6944acac38f2.png) |
| Enhanced | ![2x2x2-diff-x](https://user-images.githubusercontent.com/9214917/104056076-28984200-51f0-11eb-8c8f-e2cde18da3bb.jpg) | ![32x32x32-diff-x](https://user-images.githubusercontent.com/9214917/104056128-3fd72f80-51f0-11eb-803b-3aaf347d20e8.jpg) |

There are also differences when brighter sRGB input colors are used, but those are much harder to notice:

| | 2³ | 32³ |
|-|-|-|
| Diff | ![diff-2x2x2](https://user-images.githubusercontent.com/9214917/104057647-cdb41a00-51f2-11eb-9ac3-be9164714f05.jpg) | ![diff-32x32x32](https://user-images.githubusercontent.com/9214917/104057682-dc023600-51f2-11eb-81ab-3fc3d8439b19.jpg) |
| Enhanced | ![diff-2x2x2-t](https://user-images.githubusercontent.com/9214917/104057653-d147a100-51f2-11eb-8ea8-f42c727a063c.jpg) | ![diff-32x32x32-t](https://user-images.githubusercontent.com/9214917/104057690-defd2680-51f2-11eb-8e76-938c2f94d347.jpg) |

> Regarding the UVW calculation the 2D LUT sampling function is intended to sample colors in the same way as the texture 3d sampling function so the input for both functions should be the same.

Got it. That just stuck out to me because the shader is calculating the actual texel height using size² [here](https://github.com/gkjohnson/threejs-sandbox/blob/704384775c5774c1749200ca7bb31f100366caab/3d-lut/src/shaders/LUTShaderFunctions.js#L6) while the scale/offset calculation assumes a square texel size. I've also come across some implementations that calculate the scale/offset a bit differently for the 2D case: [line 254](https://www.shadertoy.com/view/4dyBWD).

**Comment by gkjohnson** [comment] 2021-01-08 20:23
Got it -- how are you generating the diffs? Are you just comparing the sampled values in the shader? And is the difference noticeable visually?

**Comment by vanruesc** [comment] 2021-01-08 20:35
I'm using https://www.diffchecker.com/image-diff and I saved the results as compressed JPGs. This could indeed exaggerate the differences, but if the source images were identical, compression wouldn't matter. The difference is not very noticeable.

**Comment by gkjohnson** [comment] 2021-01-09 01:15
Good to know that looks like a useful site!

If the visual result looks good I think I'm content to leave it for now. I won't rule out the sampling function still having some issues but with more calculations happening in the 2d sampling case I'd imagine you'd get some differences from floating rounding error, as well, so aiming for literally identical images may be an impossible goal.

And after taking a quick look at the TetrahedralUpscaler again I don't think the sampling approach needs to be adjusted as I suggested in https://github.com/vanruesc/postprocessing/issues/250#issuecomment-755074282 and the visual result looks okay so I think that component is good.

**Comment by vanruesc** [comment] 2021-01-09 18:35
This should now be fixed in `postprocessing@6.19.1`.

@AlexDaniel It would be great if you could take a look at the [updated demo](https://vanruesc.github.io/postprocessing/public/demo/#color-grading) to check if you notice any remaining issues. I'll keep this issue open until we're certain that everything's fixed.

@gkjohnson I've added a unit test for the TetrahedralUpscaler which confirms that it generates accurate data. The test scales a neutral LUT of size 4³ up to 32³ and compares it with a baseline neutral LUT of size 32³. The difference of individual values is below `1e-7` which is floating point inaccuracy territory.

**Comment by AlexDaniel** [comment] 2021-01-09 22:54
@vanruesc My main concern was that the previous implementation was, frankly, pretty close to being unusable. When creating luts in separate software, the are certain expectations as to how the LUT will behave, and having banding (!!) or differences in colors was making it questionable whether trying to use this was worth the trouble.

Looking at the last demo, all of that has been fixed. My only use case is color grading, so I see no issues whatsoever. This is absolutely fantastic, and all the extras like upscaling make me so happy. For me, there's nothing left to do, it is perfect.

That said, I do have some additional comments, but all of this is extra that won't make my life any easier.

When it comes to working with video, there's this idea of having generational stability. [Some explanation](https://support.newtek.com/hc/en-us/articles/218109667-NDI-Encoding-Decoding):

> The peak signal-to-noise ratio (PSNR) of the NDI codec exceeds 70dB for typical video content. Uniquely, and importantly, NDI is the first ever codec to provide multi-generational stability. This means that once a video signal is compressed, there is no further loss. As a practical example, generation 2 and generation 1000 of a decode-to-encode sequence would be identical.

This may sound too good to be true, and it is. NDI in obs-studio actually fails completely to do that, so there is more marketing fluff in that than actual substance. As you can imagine, it may be related to colorspace conversions, and maybe the actual issue is not in NDI itself. But their SDK is not open-source, so who freaking knows. (By the way, here's a [fun story](https://trac.ffmpeg.org/ticket/7589) about their SDK and GPL violations)

But this brings the question. If you take an image that has all possible sRGB colors (let's say a PNG from [here](http://www.brucelindbloom.com/index.html?RGB16Million.html)), and apply a neutral LUT on that, what happens? Does it produce exactly the same output on the first generation? If not, when does it stabilize? I could try this myself but I guess you were already writing a test for doing something like that.

My understanding is that it does *not* produce the same result on the first step. Testing this seems to be surprisingly easy in the demo itself. In the `blend mode`, choose `DIFFERENCE` (other options like `SUBTRACT` also seem to work?). You'll see this:

![image](https://user-images.githubusercontent.com/5507503/104109883-e992eb00-52da-11eb-92c8-3717c95c9f95.png)

So what's the meaning of the `DIFFERENCE` blend mode in this case, and why are we seeing this?

As for comparing the images, the easiest tool is probably imagemagick's [`compare`](https://imagemagick.org/script/compare.php):

```bash
compare a.png b.png diff.png
```

And here's the output:

![diff](https://user-images.githubusercontent.com/5507503/104109916-42628380-52db-11eb-94d3-23a8cbe91bfa.png)

(3D texture is not selected on the screenshot, but the result seems to be the same regardless of that setting)

While this is completely unnoticeable to the eye, a lot of pixels seem to be off. Generational stability does matter in some use cases. Let's say you were making a LUT-based node editor to create some sort of image processing tool in three.js. If there's no generational stability, then just adding more nodes (even if they do nothing) will increasingly distort the final image.

Note, however, that even if that is fixed, more extreme LUTs can later reveal more issues. That is, the values in the LUT can be very peaky so to say, so that the interpolation between the values has a much harder time. The testing will need to be done in two steps though, so the first LUT should distort the colors to some precisely predicted values, and a second LUT will then need to restore them. This is actually a fascinating topic, it'd be very interesting to create a sort of LUT stress test suite and see how different software behaves. However, that is a completely different can of worms and I personally don't need any of that, although I'm very curious.

**Comment by AlexDaniel** [comment] 2021-01-10 09:49
Actually, you can probably ignore the blend mode stuff. Now that I look at it, it's probably caused by pixels that are way too bright. Hm, actually, what's the behavior for colors outside the LUT range? Either way, it's not an issue I think, but the diff done by imagemagick is.

**Comment by vanruesc** [comment] 2021-01-10 14:46
> My main concern was that the previous implementation was, frankly, pretty close to being unusable. 

I agree and I appreciate your feedback. I expected minor bugs but didn't know enough about LUTs to spot these issues.

> So what's the meaning of the DIFFERENCE blend mode in this case, and why are we seeing this?

`DIFFERENCE` does `abs(oldColor - newColor)` and `SUBTRACT` does `max(oldColor + newColor - 1.0, 0.0)`.

> Now that I look at it, it's probably caused by pixels that are way too bright. 

Right, since we're using `HalfFloatType` buffer, colors can be greater than `1.0`. You'd normally use tone mapping before applying the LUT to map HDR to LDR first. The demo currently doesn't do that, but it probably should since there are bright highlights. The `LUTEffect` always clamps input values to `[0.0, 1.0]`, either via the 3D texture wrap mode [ClampToEdgeWrapping](https://github.com/vanruesc/postprocessing/blob/94188909eb80f09a14829c8c2c828684371b5c78/src/images/textures/LookupTexture3D.js#L53-L55) or manually [in the shader](https://github.com/vanruesc/postprocessing/blob/94188909eb80f09a14829c8c2c828684371b5c78/src/effects/glsl/lut/shader.frag#L97) when a 2D texture is used.

> While this is completely unnoticeable to the eye, a lot of pixels seem to be off.

As @gkjohnson pointed out, we can't avoid floating point rounding issues. If you type `0.4 * 0.4` in your browser's console, you'll get `0.16000000000000003` which already differs from `0.16`. Perfect generational stability would probably require rounding error safe guards in the interpolations which would be unfeasible.

> If you take an image that has all possible sRGB colors (let's say a PNG from here), and apply a neutral LUT on that, what happens? Does it produce exactly the same output on the first generation? If not, when does it stabilize?

In theory it should but in practice you'll get floating point rounding errors and the result will rarely, if ever, match perfectly. It would never stabilize; errors would accumulate. At least that's what I'd expect.

> 3D texture is not selected on the screenshot

If there is a difference between the 3D/2D sampling algorithms then I'd assume the 3D sampling to be more accurate and less error-prone since it's only doing this: `texture(lut, rgb)`

What could further improve accuracy is tetrahedral interpolation inside the shader.

**Comment by AlexDaniel** [comment] 2021-01-11 00:02
> As @gkjohnson pointed out, we can't avoid floating point rounding issues. If you type 0.4 * 0.4 in your browser's console, you'll get 0.16000000000000003 which already differs from 0.16. Perfect generational stability would probably require rounding error safe guards in the interpolations which would be unfeasible.

> In theory it should but in practice you'll get floating point rounding errors and the result will rarely, if ever, match perfectly. It would never stabilize; errors would accumulate. At least that's what I'd expect.

Well, not exactly. That value (0.16000000000000003) will still map to the same color on the screen. And that's the issue currently – the values on the screen are off, not that their floating point representation is not spot on.

> The LUTEffect always clamps input values to [0.0, 1.0],

Hmmmm. I think that's something to think about. For example, Davinci Resolve does allow a node to go above the limits, and then the next node can bring the colors back into the usable range. Here's [an article](https://www.provideocoalition.com/solutions-to-resolve-part-3-unexpected-clipping-when-grading/) that talks about it.

I don't know, maybe the clamping should be configurable, or maybe there's a way to make it work outside the range (even if at first it sounds like that doesn't make any sense).

**Comment by vanruesc** [comment] 2021-01-11 01:55
> That value will still map to the same color on the screen.

Tiny float imprecisions can flip bits in the final uint8 image. I'm not saying that this is the root cause, but it can contribute to the differences between the original data rendered to screen and the interpolated data rendered to screen.

I'm currently looking into the tretrahedral interpolation shader from [OpenColorIO](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/OpenColorIO/ops/lut3d/Lut3DOpGPU.cpp) and noticed [this comment](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/d71748bf79b3bf9e297dc53bb98e0093955932df/src/OpenColorIO/ops/lut3d/Lut3DOpGPU.cpp#L218-L219). Hardware quantization of fractions down to 8 bit could be the reason why we're still seeing errors.

> maybe the clamping should be configurable

Custom input domains could be implemented by adding a range check to the input values in the shader. I'll keep it in mind.

**Comment by vanruesc** [comment] 2021-01-12 18:03
I've investigated this further and ended up implementing tetrahedral interpolation and custom input domains. I found out that the noisy errors we're still seeing are indeed caused by hardware interpolation. This [article by iq](https://www.iquilezles.org/www/articles/hwinterpolation/hwinterpolation.htm) explains the details.

The tetrahedral interpolation algorithm performs all interpolations manually to avoid the quantization of fractional components. The following comparison shows the difference between the input colors and the output colors of the `LUTEffect` using a neutral 2³ LUT:

| HW Trilinear 2D | HW Trilinear 3D | Manual Tetrahedral 3D |
|-|-|-|
| ![trilinear_2x2x2_2d](https://user-images.githubusercontent.com/9214917/104351115-42de6280-5505-11eb-8665-0b7b05b8c0f3.png) | ![trilinear_2x2x2_3d](https://user-images.githubusercontent.com/9214917/104351142-4e318e00-5505-11eb-9446-6a26c7f6e64e.png) | ![tetrahedral_2x2x2_3d](https://user-images.githubusercontent.com/9214917/104351199-64d7e500-5505-11eb-8e0a-4de6dfbd654f.png) |

Tetrahedral interpolation eliminates all remaining errors.

@gkjohnson FYI: I learned that fract() actually uses floor() internally: ["This is calculated as x - floor(x)."](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/fract.xhtml). So the following is probably a bit more efficient for the 2D sampling algorithm:
```glsl
float slice0 = floor(slice);
float interp = slice - slice0;
```

**Closed** 2021-01-12 19:54 UTC
Labels: bug

**Comment by vanruesc** [comment] 2021-01-12 20:04
Fixed in `postprocessing@6.19.2`.

The visual differences between tetrahedral interpolation and built-in trilinear interpolation are very hard to spot unless they are highlighted. Tetrahedral interpolation can be enabled via `LUTEffect.setTetrahedralInterpolationEnabled(true)` if high accuracy is desired, but trilinear interpolation remains the default as it is faster and produces great results.

**Comment by gkjohnson** [comment] 2021-01-12 20:15
Looks great! And thanks for the links and extra research.

**Comment by AlexDaniel** [comment] 2021-01-13 00:09
Absolutely fantastic!

I did some tests:
| neutral-8, 3D | neutral-8, 3D + tetrahedral | neutral-8, 3D + tetrahedral + upscale |  neutral-8, 3D + tetrahedral + upscale 128 |
|-----|-----|-----|-----|
| ![diff-b](https://user-images.githubusercontent.com/5507503/104389233-ab4c3480-5543-11eb-89f9-4cd15fec0f67.png) | ![diff-c](https://user-images.githubusercontent.com/5507503/104389236-ad15f800-5543-11eb-9433-9af5ceabf420.png) | ![diff-d](https://user-images.githubusercontent.com/5507503/104389241-b0a97f00-5543-11eb-8a2c-92b17825692f.png) | ![diff-e](https://user-images.githubusercontent.com/5507503/104389426-1a298d80-5544-11eb-83ad-2679d3879817.png) |

If we're speaking about neutral luts and pixel-perfect results, then looking at the results above, turning on tetrahedral interpolation gives the biggest win, while upscaling makes no difference whatsoever (as long as tetrahedral interpolation is on).

**Comment by gkjohnson** [comment] 2021-01-13 00:34
> while upscaling makes no difference whatsoever (as long as tetrahedral interpolation is on)

I wouldn't expect tetrahedral upscaling on the CPU to make a difference if you're using tetrahedral sampling on the GPU. Tetrahedral sampling in the shader is likely much more expensive than just performing trilinear sampling with the 3d texture so it's a trade you can make.
