### ISSUE TITLE
Messing up loaded .obj geometry (hidden vertices?)

### ISSUE THREAD

**Issue by mchrbn** [vanruesc/postprocessing#71] opened 2018-03-10 08:31 UTC
Hello,

First of all very great library, the effects are beautiful! 

I'm having an issue with loaded .obj models. No matter which pass I apply (except the RenderPass), one of my model (random) will have its geometry messed up (some vertices are non visible).

I have set up an example here, where you can see that one of the cube will be almost non existant: http://mchrbn.net/test/

My JS code here: https://pastebin.com/78HQpceD (from line 64)

Tests I did:
- It seems to happen only with loaded models, with three.js internal objects it works fine (ie: BoxGeometry, ...)
- I do not have this problem with the postprocessing library used on the three.js website

Version of the library: 4.3.2
The issue happens on various browsers, even Internet Explorer.

Thanks!

**Comment by vanruesc** [comment] 2018-03-10 13:07
Hi,

thanks for reporting this issue!

This bug looks quite weird - my first guess is that it might not be caused by the postprocessing library. I'll take a closer look in a bit.

**Comment by vanruesc** [comment] 2018-03-10 15:13
I've created a [minimal example](https://jsfiddle.net/c2onwtpr/11/) on JSFiddle which uses the OBJLoader to load a model from the `three.js` examples. I wasn't able to reproduce your problem with this setup.

It would be helpful if you could provide the models that you're loading in your example. We can then plug them into the fiddle (line 88) and see if it breaks.

Some additional hints:
 - `computeFaceNormals` is deprecated and doesn't do anything in `three.js@r90`
 - `computeVertexNormals` may produce incorrect normals for your models (although unlikely).
 - `antialias` doesn't work when post processing effects are active. It should be disabled to improve performance. The alternative is to use an antialiasing pass like the `SMAAPass`.
 - In your `onResize` handler you should replace `renderer.setSize(window.innerWidth, window.innerHeight);` with `composer.setSize(window.innerWidth, window.innerHeight);`

**Comment by mchrbn** [comment] 2018-03-12 08:12
Thanks for your answer and the additional hints !

It's working now, what I changed is simply using your built file (postprocessing.min.js) rather than importing postprocessing with `import { EffectComposer, FilmPass, GlitchMode, GlitchPass, RenderPass } from 'postprocessing';`.

So the built file shows all my models well while the import method is messing up one object.

**Comment by vanruesc** [comment] 2018-03-12 12:32
> It's working now, what I changed is simply using your built file (postprocessing.min.js)

I'm glad that it works for you now 😄 However, I can't help but feel a little worried about this solution.

The reason why I don't think that the postprocessing library is causing this issue is that the various passes operate on the _output_ of the `RenderPass` - only the `RenderPass` actually uses your scene and camera. The logical conclusion would be that the other passes can't mess up the geometry since they never touch it in the first place.

If your issue would occur with the `OutlinePass` or the `GodRaysPass` then there would be reason to believe that the library is doing something wrong, but since the issue occurs with pure image filter passes like the `GlitchPass` it just seems very unlikely.

The built file is a transpiled version of the library - the logic should be exactly the same. The only way to locate the real issue is to reproduce the bug with no other libraries involved using your OBJ models.

I'm closing this issue since there is no clear indication of an actual bug in the library.
If you wish to persue this further, we can always reopen it.

**Comment by mchrbn** [comment] 2018-03-12 13:23
I'm personally fine with using your built file, but yes it is a bit odd because this the same code worked fine with both your built file and the native postprocessing library from three.js. I only encountered the issue with the library version. I'm using webpack to pack everything together so maybe this process messes-up something?

Not sure I can help much but I will still try to investigate this further and message you if I find anything!

Thanks again.

**Comment by vanruesc** [comment] 2018-03-23 12:39
Closing for now due to inactivity.

**Closed by vanruesc** 2018-03-23 12:39 UTC
Labels: troubleshooting

**Comment by funwithtriangles** [comment] 2019-04-09 10:27
I'm having a similar issue. My models are messing up when I'm using this library. I have quite a complex setup so I'm sure it's going to be hard to replicate. It appears to only be `SkinnedMesh` that's affected. Will report back if I can work out what has caused this!
