### ISSUE TITLE
SSR pass

### ISSUE THREAD

**Issue by MrMateo7** [vanruesc/postprocessing#348] opened 2022-02-22 17:45 UTC
### Is your feature request related to a problem?

Would be great to have this pass. This is a live example https://threejs.org/examples/?q=ssr#webgl_postprocessing_ssr

or thinking about performance, in this case https://sketchfab.com/3d-models/art-gallery-720b507d814740278c713d100def4c99 the quality is variable.

**Comment by vanruesc** [comment] 2022-02-22 20:44
Duplicate of #190. SSR is already on the roadmap #279. Thanks for the additional resources!

**Closed by vanruesc** 2022-02-22 20:44 UTC
Labels: duplicate, feature request
