### ISSUE TITLE
Angular CLI build --prod issue

### ISSUE THREAD

**Issue by patrickrb** [vanruesc/postprocessing#61] opened 2017-09-10 05:14 UTC
I've added postprocessing to my project, but when I try to build it, I get the following error:

```
ERROR in vendor.f88364d9ba59a6c23726.bundle.js from UglifyJs
Unexpected token: name (AdaptiveLuminosityMaterial_AdaptiveLuminosityMaterial) [vendor.f88364d9ba59a6c23726.bundle.js:124902,6]
```

From what I've read, it has something to do with es6?  It bulds fine as long as it doesn't run through uglify.  Any help would be greatly appreciated.

Thanks!

**Comment by vanruesc** [comment] 2017-09-10 11:18
Hi,

you're right; UgilfyJS still doesn't support ES2015+ syntax and judging by the error you've given, your bundling tool reads the `postprocessing` source code directly via the [module](https://github.com/vanruesc/postprocessing/blob/master/package.json#L7) entry point. That's the intended behaviour, since the bundler can then exclude unused imports.

If you configure your build setup to transpile your final bundle with [babel](https://github.com/babel/babel) __before__ feeding it to UglifyJS, you'll be fine. In case all other dependencies in your project are already ES5 code, you could also configure your bundler to use the [main](https://github.com/vanruesc/postprocessing/blob/master/package.json#L6) entry point instead which points to a transpiled ES5 version of the `postprocessing` library. Keep in mind though, that this approach is suboptimal.

You could also try out [babel-minify](https://github.com/babel/minify) (previously called babili), but this minifier might not be suitable for production yet.

**Comment by vanruesc** [comment] 2017-09-12 23:56
Closing this since the issue seems to be resolved.

**Closed by vanruesc** 2017-09-12 23:56 UTC
Labels: question
