### ISSUE TITLE
Add example of Pass that writes in a renderTarget before

### ISSUE THREAD

**Issue by marcofugaro** [vanruesc/postprocessing#299] opened 2021-05-19 15:47 UTC
### Is your feature request related to a problem?

I can't figure out how to write to a custom `renderTarget` while rendering in a Pass. I have the following code:

```js
import * as THREE from 'three'
import { Resizer, Pass } from 'postprocessing'

export class MyCustomPass extends Pass {
  constructor() {
    super('MyCustomPass')

    this.setFullscreenMaterial(
      new THREE.ShaderMaterial({
        blending: THREE.NoBlending,
        depthWrite: false,
        depthTest: false,
        toneMapped: false,

        uniforms: {
          inputBuffer: { value: null },
          renderTargetTexture: { value: null },
        },

        vertexShader: /* glsl */ `
          varying vec2 vUv;

          void main() {
            vUv = position.xy * 0.5 + 0.5;
            gl_Position = vec4(position.xy, 1.0, 1.0);
          }
        `,
        fragmentShader: /* glsl */ `
          uniform sampler2D inputBuffer;
          uniform sampler2D renderTargetTexture;
          varying vec2 vUv;

          void main() {
            // vec4 texel = texture2D(inputBuffer, vUv); // this works as expected
            vec4 texel = texture2D(renderTargetTexture, vUv); // this doesn't work
            gl_FragColor = texel; 

            // Support automatic output encoding.
            #include <encodings_fragment>
          }
        `,
      })
    )
    this.needsSwap = false

    // create a custom renderTarget here
    this.renderTarget = new THREE.WebGLRenderTarget(1, 1, {
      minFilter: THREE.LinearFilter,
      magFilter: THREE.LinearFilter,
      format: THREE.RGBAFormat,
      stencilBuffer: false,
      depthBuffer: false,
    })
    this.renderTarget.texture.name = 'MyCustomPass.Target'
    this.renderTarget.texture.generateMipmaps = false

    this.resolution = new Resizer(this, Resizer.AUTO_SIZE, Resizer.AUTO_SIZE)
  }

  render(renderer, inputBuffer, outputBuffer, deltaTime, stencilTest) {
    const material = this.getFullscreenMaterial()

    // first render everything in the rendertarget
    renderer.setRenderTarget(this.renderTarget)
    renderer.render(this.scene, this.camera)

    // then render from the rendertarget to the main
    material.uniforms.renderTargetTexture.value = this.renderTarget.texture 
    material.uniforms.inputBuffer.value = inputBuffer.texture
    renderer.setRenderTarget(this.renderToScreen ? null : outputBuffer)
    renderer.render(this.scene, this.camera)
  }

  setSize(width, height) {
    this.resolution.base.set(width, height)

    this.renderTarget.setSize(this.resolution.width, this.resolution.height)
  }

  initialize(renderer, alpha, frameBufferType) {
    if (frameBufferType !== undefined && frameBufferType !== THREE.UnsignedByteType) {
      const material = this.getFullscreenMaterial()
      material.defines.FRAMEBUFFER_PRECISION_HIGH = '1'
    }
  }
}
```

I need this code for an effect, however when I render this, this happens:

![image](https://user-images.githubusercontent.com/7217420/118843267-2f377400-b8ca-11eb-82ad-cd021f77c153.png)

Do you have any idea why? Would be nice if the custom Pass/Effect guides could go more in-depth.

**Comment by marcofugaro** [comment] 2021-05-19 16:51
UPDATE: I found out that `this.scene` and `this.camera` are not the scene and camera passed to the composer.

The above example works if I use the original scene and camera:

```js
// first render everything in the rendertarget
renderer.setRenderTarget(this.renderTarget)
renderer.render(this.myScene, this.myCamera)
```

However I encountered another issue. My pass is ignored if I add another `EffectPass` after, for example:
```js
const renderPass = new RenderPass(scene, camera)
composer.addPass(renderPass)

// this is somehow ignored if there is another pass after
const myCustomPass = new MyCustomPass(scene, camera)
composer.addPass(myCustomPass)

const smaaEffect = new SMAAEffect(...smaa)
const effectPass = new EffectPass(camera, smaaEffect)
composer.addPass(effectPass)
```

any idea why is that? Should I convert my Pass to an Effect? How do I do that?

**Comment by vanruesc** [comment] 2021-05-19 18:17
> My pass is ignored if I add another EffectPass after

This is because `needsSwap` is set to `false`. The custom pass renders the main scene into the render target, then it renders the result into the `outputBuffer`. The `EffectComposer` sees the `needsSwap` flag and feeds the empty `inputBuffer` into the `EffectPass`.

> Should I convert my Pass to an Effect? How do I do that?

<details><summary>This is how the pass would look like as an Effect:</summary>
<p>

```js
import { LinearFilter, RGBAFormat, Uniform, WebGLRenderTarget } from "three";
import { Effect, RenderPass, Resizer } from "postprocessing";

const fragmentShader = `#ifdef FRAMEBUFFER_PRECISION_HIGH

	uniform mediump sampler2D myTexture;

#else

	uniform lowp sampler2D myTexture;

#endif

void mainImage(const in vec4 inputColor, const in vec2 uv, out vec4 outputColor) {

	outputColor = texture2D(myTexture, uv);

}`;

export class CustomEffect extends Effect {

	constructor(scene, camera) {

		super("CustomEffect", fragmentShader, {
			uniforms: new Map([
				["myTexture", new Uniform(null)]
			])
		});

		this.renderPass = new RenderPass(scene, camera);

		this.renderTarget = new WebGLRenderTarget(1, 1, {
			//type: UnsignedByteType,
			minFilter: LinearFilter,
			magFilter: LinearFilter,
			format: RGBAFormat,
			stencilBuffer: false,
			depthBuffer: false
		});

		this.renderTarget.texture.name = "CustomEffect.Target"
		this.renderTarget.texture.generateMipmaps = false;
		this.uniforms.get("myTexture").value = this.renderTarget.texture;

		this.resolution = new Resizer(this, Resizer.AUTO_SIZE, Resizer.AUTO_SIZE);

	}

	update(renderer, inputBuffer, deltaTime) {

		this.renderPass.render(renderer, this.renderTarget);

	}

	setSize(width, height) {

		const resolution = this.resolution;
		resolution.base.set(width, height);

		const w = resolution.width;
		const h = resolution.height;

		this.renderTarget.setSize(w, h);

	}

	initialize(renderer, alpha, frameBufferType) {

		this.renderTarget.texture.type = frameBufferType;

	}

}
```

</p>
</details>

The fact that `needsSwap` can be so annoying and that the `RenderPass` actually renders into the `inputBuffer` are both issues which will be addressed by the planned frame buffer management system.

> Would be nice if the custom Pass/Effect guides could go more in-depth.

Agreed. I'll update the Wiki entries when the next major release is done.

**Comment by marcofugaro** [comment] 2021-05-19 20:01
Thanks! The `needSwap` did the trick!
Yes the "create custom" part of the wiki needs more work, have you considered putting it on a website so other people can contribute as well?

-----------

BTW now the issue I have is that SMAA is not affecting the output from the pass before, maybe it's because the background is transparent? I have no idea.

![image](https://user-images.githubusercontent.com/7217420/118875423-53a44800-b8ec-11eb-8792-23bf3434fd69.png)


this is the setup I'm using:
```js
const renderPass = new RenderPass(scene, camera)
composer.addPass(renderPass)

const myCustomPass = new MyCustomPass(scene, camera)
composer.addPass(myCustomPass)

const smaaEffect = new SMAAEffect(...smaa)
const effectPass = new EffectPass(camera, smaaEffect)
composer.addPass(effectPass)
```

**Comment by vanruesc** [comment] 2021-05-20 10:05
> have you considered putting it on a website so other people can contribute as well?

Do you mean something like a forum? Maybe we could use [GitHub Discussions](https://github.com/vanruesc/postprocessing/discussions) for this, with a dedicated "Guides" category. I'd like to keep the Wiki pages as primary resources though.

> now the issue I have is that SMAA is not affecting the output from the pass before

At what resolution does your custom pass render? SMAA can only detect aliasing artifacts at the resolution at which it's being rendered. If you feed it low-res images, the large aliasing artifacts will be dismissed as intentional texture details.

Also, the way effect merging works is that all effects in the `EffectPass` instance use the same `inputBuffer` which is the result of your initial `RenderPass` in this case. SMAA's edge detection will operate on this `inputBuffer` and not on the intermediate output of your custom effect. To allow SMAA to antialias your custom output, you need to apply SMAA in a separate pass.

> the output appears lighter in color now somehow, why is that?

No clue. I'd need a reproduction of the issue to find the root cause.

**Comment by marcofugaro** [comment] 2021-05-20 17:57
> Do you mean something like a forum? Maybe we could use GitHub Discussions for this, with a dedicated "Guides" category. I'd like to keep the Wiki pages as primary resources though.

I meant something like the [three.js' docs](https://github.com/mrdoob/three.js/tree/dev/docs) which live in the repo and people can make PRs to it.

> No clue. I'd need a reproduction of the issue to find the root cause.

Basically I'm trying to make a crisp outline effect for a project:


![image](https://user-images.githubusercontent.com/7217420/119024832-ccb2a680-b9a3-11eb-8321-c68637b0f134.png)

I've found the [pixel-outline-pass](https://gkjohnson.github.io/threejs-sandbox/pixel-outline-pass/) and I'm trying to convert it to use your postprocessing library.

Here is my current progress:

<img src="https://user-images.githubusercontent.com/7217420/119025108-17342300-b9a4-11eb-8a76-340fb256f101.png" width="300">

It's online here: [https://codesandbox.io/s/postprocessing-outline-2idu7](https://codesandbox.io/s/postprocessing-outline-2idu7?file=/src/index.js)

And this is the relevant code:

```js
// init postprocessing
const composer = new EffectComposer(webgl.renderer, {
  frameBufferType: THREE.HalfFloatType,
})
composer.addPass(new RenderPass(webgl.scene, webgl.camera))

// add PixelOutlinePass
const pixelOutlinePass = new PixelOutlinePass(webgl.scene, webgl.camera, {
  color: '#000000',
  thickness: 5,
})
// 1. This works correctly however does not get antialiased
composer.addPass(pixelOutlinePass)

const pixelOutlineEffect = new PixelOutlineEffect(webgl.scene, webgl.camera, {
  color: '#000000',
  thickness: 5,
})
// 2. This somehow makes the whole thing lighter in tones
// composer.addPass(new EffectPass(webgl.camera, pixelOutlineEffect))

// add SMAA
new SMAAImageLoader().load(([search, area]) => {
  const smaaEffect = new SMAAEffect(search, area)
  const effectPass = new EffectPass(webgl.camera, smaaEffect)
  composer.addPass(effectPass)
})
```

As you can see

1. I can't get the outline to antialias
2. If I use the effect (comment out the pass and uncomment the effect line) the image somehow is lighter in tones

<img src="https://user-images.githubusercontent.com/7217420/119026327-52832180-b9a5-11eb-8dbd-6ce3c8d2e0f6.png" width="300" />

**Comment by vanruesc** [comment] 2021-05-21 09:34
Thanks for the redprocution! This was indeed a bit tricky to debug.

> If I use the effect (comment out the pass and uncomment the effect line) the image somehow is lighter in tones:

Sorry, that was my fault: I didn't set the blend function of the effect to `NORMAL` (default is `SCREEN`).

> I can't get the outline to antialias

That's because the outline color is the same color as the background (rgba(0,0,0,0). SMAA only looks at color, not alpha. I think this can be considered a bug, although the original implementation also doesn't consider alpha edges, probably for performance reasons.

If you set the edge color to a different color or disable alpha, antialiasing will work properly:

| No SMAA, No Outline | No SMAA | SMAA Edges | SMAA, Black Outline | SMAA, Red Outline |
|-|-|-|-|-|
| ![smaa-00](https://user-images.githubusercontent.com/9214917/119115633-acc4c680-ba27-11eb-9d57-b492cf5fe868.jpg) | ![smaa-02](https://user-images.githubusercontent.com/9214917/119115806-ded62880-ba27-11eb-8f9c-40806e360bde.jpg) | ![smaa-edges](https://user-images.githubusercontent.com/9214917/119115672-b8b08880-ba27-11eb-9509-9e10db3cdd5a.jpg) | ![smaa-03](https://user-images.githubusercontent.com/9214917/119115961-0fb65d80-ba28-11eb-871d-e7f099e2cf9a.jpg) | ![smaa-04](https://user-images.githubusercontent.com/9214917/119116074-307eb300-ba28-11eb-91c1-2a1829f7c5cc.jpg) |

Fixed sandbox: https://codesandbox.io/s/postprocessing-outline-forked-8wz9x?file=/src/index.js

**Comment by vanruesc** [comment] 2021-05-21 14:09
> I meant something like the three.js' docs which live in the repo and people can make PRs to it.

I'd like to keep the documentation in the code as doc comments. Maintaining docs separately is not something I'm considering at the moment.

**Comment by marcofugaro** [comment] 2021-05-21 18:04
Thanks a lot! So weird that is the only use-case where SMAA has no effect, black on transparent edges.

Anyway, I ended up removing the alpha altogether (chroma keying the border after antialias was a no-go). Thanks for your help!

Here is the final setup, I apply the white background as a postprocessing effect because I need to do LUT before, and it would mess up the white:

```js
const effectPass = new EffectPass(camera, lutEffect, pixelOutlineEffect, backgroundEffect)
const effectPass2 = new EffectPass(camera, smaaEffect)
composer.addPass(effectPass)
composer.addPass(effectPass2)
```

You can close this issue now if you want!

**Closed** 2021-05-21 18:17 UTC
Labels: support
