### ISSUE TITLE
Render the same scene with more composers and cameras

### ISSUE THREAD

**Issue by emmelleppi** [vanruesc/postprocessing#257] opened 2021-01-20 20:55 UTC
Hello! I'm sorry to open a new issue but I haven't found a solution among the previous issues

### Description of the bug

The scenario is as follows:
- 1 scene
- 2 composer: one that renders the scene directly to the screen, the other is used with lower resolution (512x512) to save the scene seen from a virtual camera (in order to create a reflector)
- 2 camera: the main camera, and the virtual camera for the reflector

The postprocessing pipeline is therefore as follows:
```js
    const composer = new EffectComposer(renderer, { frameBufferType: HalfFloatType, multisampling: 0 })
    composer.setSize(screenWidth, screenHeight)

    const targetComposer = new EffectComposer(renderer, { frameBufferType: HalfFloatType, multisampling: 0 })
    targetComposer.autoRenderToScreen = false
    targetComposer.setSize(512, 512)

    targetComposer.addPass(lambdaPassBefore) // <- someMesh.visible = false
    targetComposer.addPass(renderPass)
    targetComposer.addPass(savePass)
    targetComposer.addPass(lambdaPassAfter) // <- someMesh.visible = true

    composer.addPass(renderPass)

    function render(now) {
        requestAnimationFrame(render);
        targetComposer.render(clock.getDelta());
        composer.render(clock.getDelta());
    }
```

I have three significant cases:

1 - Use only the main composer (no `targetComposer.render(clock.getDelta())`)
The scene is perfect and it renders at 60fps, but obviously there is no reflector

<img width="780" alt="Schermata 2021-01-20 alle 21 23 59" src="https://user-images.githubusercontent.com/39760175/105233195-cf260080-5b69-11eb-88d9-4d3ba9deb578.png">

2 - Use both composers (ideal case)
Render everything perfectly but at 10fps, if not less

<img width="785" alt="Schermata 2021-01-20 alle 21 24 58" src="https://user-images.githubusercontent.com/39760175/105233257-e49b2a80-5b69-11eb-832b-bbd2e123a2f8.png">

3 - Use both composers, but adding an EffectPass after the main composer RenderPass
```js
    composer.addPass(renderPass)
    composer.addPass(effectPass)
```

in this case I easily reach 60fps with the reflector but the colors are wrong, it would seem almost a mapping with fewer bits, I don't really know...

<img width="785" alt="Schermata 2021-01-20 alle 21 24 38" src="https://user-images.githubusercontent.com/39760175/105233238-dbaa5900-5b69-11eb-830a-c7856c652b86.png">

Am I doing something wrong?

### To Reproduce

Here is the csb file where postprocessing is used:
https://codesandbox.io/s/r3f-ibl-envmap-simple-forked-jfrl5?file=/src/use-postprocessing.js:507-554

### Library versions used

 - Three: 0.124.0
 - Post Processing: 6.20.0

**Comment by vanruesc** [comment] 2021-01-20 23:20
The `HalfFloatType` constant is not exported by `postprocessing`. It must instead be imported from `three`. I modified the example to remove the additional composer as this approach can lead to lots of issues. For instance, using `setSize()` on a composer will also change the render size of the associated renderer. If this renderer is shared between composers, you'll get undesired results. I also recommend implementing the reflector logic as a custom pass.

https://codesandbox.io/s/r3f-ibl-envmap-simple-forked-d8c7w?file=/src/use-postprocessing.js

 [This comment](https://github.com/vanruesc/postprocessing/issues/219#issuecomment-668572380) explains the performance drop you mentioned.

**Comment by drcmda** [comment] 2021-01-21 11:22
@vanruesc we're trying to figure out a way to use pp for textures only, so that it won't take over rendering of the scene. i almost have it: https://codesandbox.io/s/r3f-ibl-envmap-simple-forked-9nqus?file=/src/use-postprocessing.js but for some reason the second pass-chain (reflector) runs very, very slow, although the buffers should be tiny - but in your box above it's 60ps. could take a quick look?

and is it correct that after execute effectcomposer with autorendertoscreen=false i have to do: gl.setRenderTarget(null) ? or else i just see a black screen.

**Comment by drcmda** [comment] 2021-01-21 11:49
ps. i did what you did above, simply adding renderpass+savepass, then letting it take over render (which i'd like to avoid) and suddenly 60fps: https://codesandbox.io/s/r3f-ibl-envmap-simple-forked-v1v36?file=/src/App.js i don't how this can be possible

**Comment by vanruesc** [comment] 2021-01-21 12:17
> and is it correct that after execute effectcomposer with autorendertoscreen=false i have to do: gl.setRenderTarget(null) ?

This is not how the composer is supposed to be used so I can't tell you what's going on there.

>  letting it take over render (which i'd like to avoid)

There are plans to make `postprocessing` behave more like a plugin rather than a replacement renderer, but that's not yet the case.

> suddenly it's faster: [...] i don't how this can be possible

This performance issue is caused by three's `outputEncoding` system which bakes color conversion codecs into shaders based on the render target. If `renderer.outputEncoding` is set to `sRGBEncoding`, then rendering the same scene into an offscreen render target and to screen will trigger shader recompilations for all involved object materials because render targets use `LinearEncoding`. This causes constant recompilation churn.

This is a known issue: mrdoob/three.js#19056

**Comment by drcmda** [comment] 2021-01-21 13:03
that one tiny bit `, encoding: gl.outputEncoding` made all the difference! thank you!

**Comment by vanruesc** [comment] 2021-01-22 14:43
Closing this as it seems to be resolved.

**Closed by vanruesc** 2021-01-22 14:43 UTC
Labels: support
