### ISSUE TITLE
Outline Effect not showing through white backgrounds but is showing through transparent ones

### ISSUE THREAD

**Issue by Liron-Toledo** [vanruesc/postprocessing#316] opened 2021-09-09 08:40 UTC
Hey there, it's me again. You've been a huge help in my previous posts. I'm hoping you can help me once again. I've noticed two cases that i'm struggling to find a work around for. 

The first is that the outline effect doesn't seem to appear properly behind white backgrounds. I've noticed this on multiple occasions. Below, you can see how it appears when behind white backgrounds vs how it normally looks
![image](https://user-images.githubusercontent.com/32307087/132650713-d7e5ad27-9429-459c-934c-a268a964f35b.png)
![image](https://user-images.githubusercontent.com/32307087/132650901-5a57a7b7-cee2-4459-b15c-4a1f32fd2e9b.png)
I assumed it was something to with the blending function i was using (THREE.NormalBlending) I did manage to get it to show up better when using THREE.AdditiveBlending but in the process, the color was lost. Not to mention AdditiveBlending seems to make everything darker which im not a fan of aesthetically speaking.  See image below:
![image](https://user-images.githubusercontent.com/32307087/132651323-bef7b8d7-1f34-405f-b904-39f9980bd729.png)
I'm not sure if there are some options I can change or perhaps i should use some sort of custom blending function? 

Then the second issues that i think is related to the first, is the fact that I'm noticing that the outline effect will show even when behind transparent or not fully opaque objects (such as a transparent plane or plane with 0.5 opacity). I'm not sure if this is also related to the blending function but would love to hear your thoughts on a potential solution to this. Ideally for me, the outline effect shouldn't show through transparent objects (I can live with showing through not fully opaque if need be) 

Would really appreciate any advice or guidance you can give me. Look forward to your reply. Thanks again!

**Comment by vanruesc** [comment] 2021-09-09 10:55
Hi,

> I'm not sure if there are some options I can change or perhaps i should use some sort of custom blending function?

The [blending](https://threejs.org/docs/?q=material#api/en/materials/Material.blending) setting of the fullscreen materials should not be changed. Instead, try changing the `blendFunction` of the `OutlineEffect` to `ALPHA` to make it work with bright backgrounds:

```js
import { BlendFunction } from "postprocessing";

const outlineEffect = new OutlineEffect(scene, camera, {
  blendFunction: BlendFunction.ALPHA // default is SCREEN
});
```

> the outline effect will show even when behind transparent or not fully opaque objects (such as a transparent plane or plane with 0.5 opacity)

This is the expected behaviour. Transparent objects (opacity value doesn't matter) don't write depth and the outline detection relies on depth. You can render your main scene, including the transparent objects, and then render the depth of transparent objects that should occlude the outlines:

```js
const occlusionScene = new Scene();
const transparentOccluders = [transparentObject0, transparentObject1, ...];

for(const occluder of transparentOccluders) {

  const clone = occluder.clone();
  clone.material = new MeshBasicMaterial();
  clone.material.colorWrite = false;
  clone.material.depthWrite = true;
  clone.material.depthTest = true;
  occlusionScene.add(clone);

}

composer.addPass(new RenderPass(scene, camera));
composer.addPass(new RenderPass(occlusionScene, camera));
composer.addPass(new EffectPass(camera, outlineEffect);
```

[&raquo; Sandbox Example](https://codesandbox.io/s/stupefied-microservice-jskc7?file=/src/App.js)

> Ideally for me, the outline effect shouldn't show through transparent objects (I can live with showing through not fully opaque if need be)

This sounds a bit contradicting since "not fully opaque" means transparent 🤔

**Comment by Liron-Toledo** [comment] 2021-09-09 11:28
Once again, thanks so much vanruesc! Ya that last sentence was a typo 😞, I meant objects that were partially transparent (rather than fully transparent). But ya didnt think about using different scenes. WIll give that a go. Setting the blendFunction to BlendFunction.ALPHA seems to make it show up behind bright backgrounds now. The color is a little darker now then i would ideally like. But I guess i can fiddle with some of the other blendFunctions otherwise this will have to do.

**Comment by vanruesc** [comment] 2021-09-24 15:07
Closing this as it seems to be resolved.

**Closed by vanruesc** 2021-09-24 15:07 UTC
Labels: support
