### ISSUE TITLE
SavePass Render Target Behaviour

### ISSUE THREAD

**Issue by GoogolHz** [vanruesc/postprocessing#165] opened 2019-12-15 18:22 UTC
It seems that savePass doesn't save when savePass.renderToScreen = true;

**Comment by vanruesc** [comment] 2019-12-15 22:21
Right, that's the intended behaviour; the `SavePass` copies the data from the input buffer to a render target or to screen. It can't do both at the same time.

You could use two `SavePass` instances in a row: the first one writes to a buffer and the second one writes to screen.

**Comment by vanruesc** [comment] 2019-12-22 12:44
Closing as this seems to be resolved.

**Closed by vanruesc** 2019-12-22 12:44 UTC
Labels: question
