### ISSUE TITLE
OutlineEffect: Support for SkinnedMesh?

### ISSUE THREAD

**Issue by funwithtriangles** [vanruesc/postprocessing#194] opened 2020-04-22 14:18 UTC
Currently `OutlineEffect` doesn't support `SkinnedMesh`. The outline shows up, but doesn't follow the animation, just stays at whatever the default pose is. This is now supported with three's own `OutlinePass`. How tricky would it be to get it working with this library? I'm willing to give it a go if I can get a bit of direction on how to do it. Thanks!

Related three.js links:
https://stackoverflow.com/questions/59786826/best-method-to-get-outline-effect-with-animated-skinned-mesh
https://github.com/mrdoob/three.js/commit/ff77da462dcdd18c2a9c842c9ee82702dc4c2d0d

**Comment by vanruesc** [comment] 2020-04-22 14:31
The `OutlineEffect` already supports skinned meshes and morph targets since `postprocessing@4.3.1` https://github.com/vanruesc/postprocessing/issues/68#issuecomment-368229393. If there's a problem with skinning, please provide an example that demonstrates the issue. I don't have a skinned mesh at hand to test with.

**Comment by funwithtriangles** [comment] 2020-04-22 15:12
I'll have a look into why it's not working for me and report back

**Comment by funwithtriangles** [comment] 2020-04-22 16:09
So the issue occurs when my selection of meshes contains both `Mesh` and `SkinnedMesh`. This isn't such a big deal, but worth noting!

**Comment by vanruesc** [comment] 2020-04-22 16:31
Thanks for digging deeper! Skinning should work even if static and dynamic meshes are selected so this could be a bug. Not sure where it's coming from, though. I'll take a closer look when I have more time. It might also be a good idea to add a skinned mesh to the outline demo for debugging purposes.

**Comment by vanruesc** [comment] 2020-04-23 14:05
I was able to replicate the issue locally with a rigged GLTF model. It looks like `three` compiles the override materials `MeshDepthMaterial` and `DepthComparisonMaterial` once and enables or disables skinning depending on which mesh gets rendered first. If a skinned mesh comes after a non-skinned mesh, the material won't be updated correctly.

| Static selected first | Animated selected first | Static after animated |
|-|-| -|
| ![skinning](https://user-images.githubusercontent.com/9214917/80104974-36316d00-8578-11ea-9c77-742b40bd463f.jpg) | ![skinning2](https://user-images.githubusercontent.com/9214917/80105028-48aba680-8578-11ea-9545-781b9d837b3c.jpg) | ![skinning3](https://user-images.githubusercontent.com/9214917/80107443-5c0c4100-857b-11ea-8a97-a3d6ebcf6d4c.jpg)

Weird things happen when non-skinned meshes are selected after the override material was compiled for skinned meshes: the outline is then all over the place because of missing animation data.

There's a good chance that this is a known issue and there might be no simple solution. I'll check later if there's already a ticket for this problem over at `three`. If there is none yet, I'll prepare a simple reproduction of the bug with override materials.

**Comment by vanruesc** [comment] 2020-04-23 14:21
As I thought, this is a known issue: https://github.com/mrdoob/three.js/issues/18533 and https://github.com/mrdoob/three.js/issues/14577 seem to be the relevant discussions.

The current behaviour of three's override material system also affects SSAO which uses a `MeshNormalMaterial` as an override material via the `NormalPass`. Furthermore, the other effects in this library - even the `SelectiveBloomEffect` - are unaffected because they don't use override materials.

**Comment by ekelokorpi** [comment] 2020-05-14 10:20
I can confirm, that `SSAOEffect` does not work with `SkinnedMesh`.

Is there any fix for this?

**Comment by vanruesc** [comment] 2020-05-14 13:01
> Is there any fix for this?

Not that I'm aware of. This issue also puts a damper on #190.

**Comment by vanruesc** [comment] 2020-06-05 22:17
A workaround for override materials with instanced and skinned meshes has been added in `postprocessing@6.14.0`. Check [this](https://github.com/vanruesc/postprocessing/wiki/Skinned-and-Instanced-Meshes) to find out how is can be used.

**Closed by vanruesc** 2020-06-05 22:17 UTC
Labels: external bug
